version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-49-109.compute-1.amazonaws.com
            port: '5432'
            database: dfuh23fatc1qr6
            ssl: true
            user: xhjiwyfquhlwvq
            password: 91011779030b90de1ed973754e9c19f898334e1cf855703335bae7d3a7afad34
            migrations: true